### ISSUE TITLE
The description is too long

### ISSUE THREAD

**Issue by Tobshub** [wasimreja/book-finder#32]
## 🚀 Feature

Reduce the initial description shown to users

**Is your feature request related to a problem? Please describe.**
Sometimes, the book description is really long, and if it isn't the book you are looking for, you might get thrown off.

**Describe the solution you'd like**
It's better to show some of the description and have an option to show the rest.

**Comment by iamHrithikRaj** [comment]
I'd like to work on this, also if possible can you add `hacktoberfest` tag on this issue?

**Comment by Tobshub** [comment]
I can't add any labels, I don't know why. I want to add hacktoberfest as well

**Comment by iamHrithikRaj** [comment]
I think the reason might be that you haven't added `hacktoberfest` in your repo. If you see there's a typo its `hactoberfest` instead of `hacktoberfest` 

<img width="283" alt="Screen Shot 2022-10-02 at 3 30 26 AM" src="https://user-images.githubusercontent.com/50907893/193429927-2eeac2c5-4ffc-4705-9335-308289d407ce.png">

**Comment by Tobshub** [comment]
can I ask why you closed this?
